version: "3.9"

services:
  datafetch:
    build: ../datafetch
    container_name: datafetch
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ALPHAVANTAGE_APIKEY=${ALPHAVANTAGE_APIKEY}
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    links:
      - datafetch:datafetch
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
  pushgateway:
    image: prom/pushgateway:v1.4.0
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=clarity89-finnhub-datasource,grafana-simple-json-datasource
    ports:
      - 3000:3000
