global:
  scrape_interval:     86400s
  evaluation_interval: 86400s

alerting:
  alertmanagers:
    - static_configs:
      - targets:

rule_files:

scrape_configs:
  - job_name: stock_feed
    static_configs:
      - targets: ['feeder:8080']
