global:
  scrape_interval:     30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: stock_price
    static_configs:
    - targets: ['exporter:8080']