global:
  scrape_interval:     60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
      - targets:

rule_files:

scrape_configs:
  - job_name: stock_price
    static_configs:
      - targets: ['grabber:8080']
