name: Docker Compose
on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "config"